# This is a basic workflow to help you get started with Actions

name: auto-publish

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: login-build-and-run
        uses: appleboy/ssh-action@master
        env:
          DIR: ${{ secrets.REMOTE_TARGET }}
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            [ -d ~/.github/gomoku ] || git clone https://github.com/zqhhh/gomoku.git ~/.github/gomoku
            cd ~/.github/gomoku && \
              git reset --hard && \
              git pull && \
              go build -o gomoku && \
              supervisorctl stop gomoku && \
              cp gomoku ~/app/gomoku && \
              supervisorctl start gomoku
